name: Remote SSH Command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 18.61.69.9
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 21
          script: ./script.sh
